/* Kitobchi — mobil UI, ko‘rinadigan AI ish jarayoni va tiklanadigan topshiriqlar */
(() => {
  const screen = document.querySelector('#screen');
  const back = document.querySelector('#backBtn');
  const settingsBtn = document.querySelector('#settingsBtn');
  let route = 'home', active = null, models = [], currentJob = null;
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const toast = s => { const t = document.querySelector('#toast'); if (!t) return; t.textContent = s; t.classList.add('show'); clearTimeout(window.__toast); window.__toast = setTimeout(() => t.classList.remove('show'), 2800); };
  const id = () => Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
  const saveActive = () => active && KitobchiStore.projects.update(active.id, active);
  const getJob = () => KitobchiStore.jobs.get();
  const setJob = patch => { const job = {...(getJob() || {}), ...patch, updatedAt: Date.now()}; KitobchiStore.jobs.set(job); currentJob = job; render(); };
  const clearJob = () => { KitobchiStore.jobs.clear(); currentJob = null; };

  function render() {
    back.style.visibility = route === 'home' ? 'hidden' : 'visible';
    settingsBtn.style.visibility = route === 'settings' ? 'hidden' : 'visible';
    currentJob = getJob();
    if (route === 'home') home(); else if (route === 'create') create(); else if (route === 'workspace') workspace(); else settings();
  }
  function nav(activeName = 'home') { return `<nav class="bottom-nav"><button class="${activeName === 'home' ? 'active' : ''}" id="navHome">⌂<small>Bosh sahifa</small></button><button class="${activeName === 'settings' ? 'active' : ''}" id="navSettings">⚙<small>Sozlamalar</small></button></nav>`; }
  function bindNav() { document.querySelector('#navHome')?.addEventListener('click', () => { route = 'home'; render(); }); document.querySelector('#navSettings')?.addEventListener('click', () => { route = 'settings'; render(); }); }
  function home() {
    const ps = KitobchiStore.projects.list();
    const job = currentJob && currentJob.status === 'running' ? `<div class="job-mini"><span class="spinner"></span><div><b>AI ishlayapti</b><small>${esc(currentJob.stage || 'Tayyorlanmoqda')} · ${currentJob.progress || 0}%</small></div><button id="resumeJob">Ko‘rish</button></div>` : '';
    screen.innerHTML = `<section class="hero"><p class="eyebrow">IJOD UCHUN MAYDON</p><h1>G‘oyangizni<br><em>kitobga aylantiring.</em></h1><p class="muted">AI bilan yozing, bezang va birgina bosishda ulashing.</p><button class="primary wide" id="new">＋ Yangi loyiha</button></section>${job}<div class="section-head"><h2>Loyihalar</h2><span>${ps.length}</span></div><div class="cards">${ps.length ? ps.map(p => `<button class="project-card" data-id="${p.id}"><span class="project-icon">${p.type === 'book' ? '▤' : p.type === 'slides' ? '▥' : '▧'}</span><span><b>${esc(p.title)}</b><small>${esc(p.typeLabel || 'Kitob')} · ${new Date(p.updatedAt || Date.now()).toLocaleDateString('uz-UZ')}</small></span><i>›</i></button>`).join('') : `<div class="empty"><div>✦</div><p>Hali loyiha yo‘q</p><small>Birinchi g‘oyangizni hoziroq boshlang.</small></div>`}</div><div class="quick-features"><div><span>✦</span><b>AI suhbat</b><small>G‘oyani aniqlaydi</small></div><div><span>▥</span><b>Slaydlar</b><small>PPT tayyorlaydi</small></div><div><span>▣</span><b>Eksport</b><small>PDF va HTML</small></div></div>${nav()}`;
    document.querySelector('#new').onclick = () => { route = 'create'; render(); }; document.querySelector('#resumeJob')?.addEventListener('click', () => { active = KitobchiStore.projects.get(currentJob.projectId); route = 'workspace'; render(); });
    document.querySelectorAll('[data-id]').forEach(x => x.onclick = () => { active = KitobchiStore.projects.get(x.dataset.id); route = 'workspace'; render(); }); bindNav();
  }
  function create() {
    screen.innerHTML = `<section class="page"><p class="eyebrow">YANGI LOYIHA</p><h1>Nima yaratamiz?</h1><p class="muted">G‘oyangizni yozing. Kitobchi uni savollar bilan aniq loyihaga aylantiradi.</p><div class="type-grid"><button class="type selected" data-type="book">📖<b>Kitob</b><small>Hikoya, roman, qo‘llanma</small></button><button class="type" data-type="slides">▥<b>Slaydlar</b><small>Ta’lim va taqdimot</small></button><button class="type" data-type="doc">▧<b>Hujjat</b><small>Universitet va biznes</small></button></div><label class="label">G‘oyangiz yoki buyruqingiz<textarea id="prompt" placeholder="Masalan: Bolalar uchun kosmos haqida rangli ertak..."></textarea></label><button class="primary wide" id="start">AI bilan boshlash →</button></section>`;
    let type = 'book'; document.querySelectorAll('.type').forEach(b => b.onclick = () => { document.querySelectorAll('.type').forEach(x => x.classList.remove('selected')); b.classList.add('selected'); type = b.dataset.type; });
    document.querySelector('#start').onclick = () => { const p = document.querySelector('#prompt').value.trim(); if (!p) return toast('Avval g‘oyangizni yozing.'); active = {id:id(), title:p.slice(0,36), type, typeLabel:type === 'book' ? 'Kitob' : type === 'slides' ? 'Slaydlar' : 'Hujjat', prompt:p, updatedAt:Date.now(), messages:[], pages:[]}; KitobchiStore.projects.create(active); route = 'workspace'; render(); };
  }
  function progressBox() { const j = currentJob; if (!j || j.projectId !== active?.id) return ''; const steps = ['Buyruqni tahlil qilish','Loyiha brifini to‘ldirish','Kontentni yaratish','Dizayn va rasmlarni tayyorlash','Saqlash va yakunlash']; const done = j.step || 0; return `<div class="agent-panel ${j.status}"><div class="agent-head"><span class="agent-orb">✦</span><div><b>AI agentlar ishlayapti</b><small>${esc(j.stage || 'Boshlanmoqda')} · ${j.progress || 0}%</small></div><span class="spinner"></span></div><div class="agent-steps">${steps.map((s,i) => `<div class="agent-step ${i < done ? 'done' : i === done && j.status === 'running' ? 'now' : ''}"><span>${i < done ? '✓' : i + 1}</span>${s}</div>`).join('')}</div>${j.error ? `<p class="error-text">${esc(j.error)}</p>` : ''}</div>`; }
  function workspace() {
    const p = active || {}; const job = currentJob && currentJob.projectId === p.id;
    screen.innerHTML = `<section class="workspace"><div class="work-title"><div><p class="eyebrow">${esc(p.typeLabel || 'LOYIHA')}</p><h1>${esc(p.title)}</h1></div><button class="more" id="delete">⋮</button></div>${progressBox()}<div class="tabs"><button class="tab active">AI suhbat</button><button class="tab" id="contentTab">Kontent</button><button class="tab" id="exportTab">Eksport</button></div><div id="workBody"><div class="chat" id="chat">${(p.messages || []).map(m => `<div class="bubble ${m.role}">${esc(m.text)}</div>`).join('')}</div><div class="composer"><textarea id="msg" placeholder="Buyruq yoki javob yozing..." ${job && currentJob.status === 'running' ? 'disabled' : ''}></textarea><button class="send" id="send" ${job && currentJob.status === 'running' ? 'disabled' : ''}>↑</button></div></div></section>`;
    document.querySelector('#send').onclick = send; document.querySelector('#msg').onkeydown = e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }; document.querySelector('#contentTab').onclick = content; document.querySelector('#exportTab').onclick = exportView; document.querySelector('#delete').onclick = () => { if (confirm('Loyihani o‘chirasizmi?')) { KitobchiStore.projects.delete(p.id); clearJob(); route = 'home'; render(); } };
  }
  async function send() {
    const input = document.querySelector('#msg'), text = input.value.trim(); if (!text || (currentJob && currentJob.status === 'running')) return;
    active.messages = active.messages || []; active.messages.push({role:'user', text}); saveActive();
    setJob({id:id(), projectId:active.id, kind:'chat', status:'running', stage:'Buyruqni tahlil qilish', progress:8, step:0, prompt:text, baseMessages:active.messages.slice(0,-1)});
    try { setJob({stage:'AI suhbat javobini tayyorlash', progress:35, step:1}); if (!models.length) models = await KitobchiAPI.models(); const chosen = KitobchiStore.settings.get().modelName || models[0]?.name?.replace('models/','') || ''; const history = (active.messages || []).slice(0,-1).map(m => ({role:m.role === 'ai' ? 'model' : 'user', parts:[{text:m.text}]})); const answer = await KitobchiAPI.generateResilient(text, chosen, history, {maxContinuations:5}); active.messages.push({role:'ai', text:answer}); saveActive(); setJob({stage:'Yakunlandi', progress:100, step:5, status:'done'}); setTimeout(clearJob, 1800); render(); } catch (e) { setJob({status:'error', stage:'Qayta urinish kerak', progress:35, error:e.message}); toast('AI javobi saqlab qolindi.'); }
  }
  async function generateContent() {
    const p=active, isSlides=p.type==='slides'; setJob({id:id(), projectId:p.id, kind:'content', status:'running', stage:'Buyruqni tahlil qilish', progress:8, step:0});
    try { setJob({stage:'AI kontentni yozmoqda', progress:35, step:2}); if (!models.length) models=await KitobchiAPI.models(); const chosen=KitobchiStore.settings.get().modelName||models[0]?.name?.replace('models/',''); const instruction=isSlides?`Mavzu: ${p.prompt}. Professional taqdimot tuzing. Faqat JSON qaytaring: {"slides":[{"title":"...","text":"...","bullets":["..."],"imagePrompt":"..."}]}. 6-10 ta slayd, o‘zbek tilida.`:`Mavzu: ${p.prompt}. Kitob uchun 6 ta sahifa tuzing. Faqat JSON: {"pages":[{"title":"...","text":"...","imagePrompt":"..."}]}`; const raw=await KitobchiAPI.generateResilient(instruction,chosen,[],{maxContinuations:8}); setJob({stage:'Dizayn va rasmlar prompti', progress:78, step:3}); const clean=raw.replace(/^```(?:json)?/i,'').replace(/```$/,'').trim(); const data=JSON.parse(clean); p.pages=(data.slides||data.pages||[]).map(x=>({...x,text:x.text||x.body||(x.bullets||[]).join(' • ')})); saveActive(); setJob({stage:'Yakunlandi',progress:100,step:5,status:'done'}); toast(`${p.pages.length} ta ${isSlides?'slayd':'sahifa'} tayyorlandi`); setTimeout(clearJob,1800); content(); } catch(e) { setJob({status:'error',stage:'Yaratishda xato',error:e.message}); toast('Ish saqlandi, qayta urinishingiz mumkin.'); content(); }
  }
  function content() { const p=active,isSlides=p.type==='slides'; screen.innerHTML=`<section class="page"><p class="eyebrow">${esc(p.typeLabel)}</p><h1>${isSlides?'Slayd studiyasi':'Kontent studiyasi'}</h1><p class="muted">AI mavzu bo‘yicha kontentni tayyorlaydi. Jarayon yuqorida bosqichma-bosqich ko‘rinadi.</p>${progressBox()}<button class="primary wide" id="gen" ${(currentJob?.status==='running')?'disabled':''}>✦ ${isSlides?'AI slaydlarni yaratish':'Kontentni yaratish'}</button>${isSlides?`<button class="secondary wide" id="ppt" ${(p.pages||[]).length?'':'disabled'}>▥ PowerPoint (.ppt) yuklab olish</button>`:''}<div class="content-list"><div class="feature"><span>${isSlides?'▥':'🎨'}</span><b>${isSlides?'PowerPoint taqdimot':'Rangli sahifalar'}</b><small>Har bir bo‘lim alohida dizayn bilan</small></div></div><div id="pages">${(p.pages||[]).map((x,i)=>`<article class="page-card slide-card"><b>${i+1}. ${esc(x.title||'Sahifa')}</b><p>${esc(x.text||'')}</p>${x.imagePrompt?`<small>🖼 ${esc(x.imagePrompt)}</small>`:''}</article>`).join('')}</div></section>`; document.querySelector('#gen').onclick=generateContent; if(isSlides) document.querySelector('#ppt').onclick=()=>KitobchiStore.export.exportPPT(p,'kitobchi-taqdimot.ppt'); }
  function exportView(){ const p=active; screen.innerHTML=`<section class="page"><p class="eyebrow">TAYYORLASH</p><h1>Yuklab oling yoki yuboring</h1><p class="muted">Loyihangiz telefoningizda saqlangan.</p><div class="export-grid"><button class="export" id="html">HTML kitob<small>Brauzerda ochiladi</small></button><button class="export" id="json">JSON loyiha<small>Zaxira nusxa</small></button><button class="export" id="pdf">Print / PDF<small>PDF sifatida saqlash</small></button><button class="export" id="share">Ulashish<small>Telegram va boshqa ilovalar</small></button></div></section>`; const html=`<html><meta charset="utf-8"><body><h1>${esc(p.title)}</h1>${(p.pages||[]).map(x=>`<h2>${esc(x.title)}</h2><p>${esc(x.text)}</p>`).join('')}</body></html>`; document.querySelector('#html').onclick=()=>KitobchiStore.export.exportHTML(html,'kitobchi.html'); document.querySelector('#json').onclick=()=>KitobchiStore.export.exportJSON(p,'kitobchi.json'); document.querySelector('#pdf').onclick=()=>KitobchiStore.export.exportPDF(html,p.title); document.querySelector('#share').onclick=()=>KitobchiStore.export.shareOrDownload(html,'kitobchi.html'); }
  function settings(){ const s=KitobchiStore.settings.get(); screen.innerHTML=`<section class="page"><p class="eyebrow">SOZLAMALAR</p><h1>Kitobchini sozlang</h1><label class="label">Gemini API kaliti<input id="key" type="password" value="${esc(s.apiKey||'')}" placeholder="AIza..." /></label><p class="hint">Kalit faqat shu telefonda saqlanadi.</p><button class="primary wide" id="save">Saqlash</button><div class="setting-card"><b>Model tanlash</b><p class="muted">Modellar Gemini API’dan avtomatik yuklanadi.</p><select id="modelSelect"><option value="">Avval modellarni yuklang</option></select><button class="secondary" id="refresh">Modellarni yuklash</button><div id="modelStatus"></div></div>${nav('settings')}</section>`; const select=document.querySelector('#modelSelect'); const fill=()=>{select.innerHTML=models.length?models.map(m=>{const n=(m.name||'').replace('models/','');return `<option value="${esc(n)}" ${n===s.modelName?'selected':''}>${esc(m.displayName||n)}</option>`}).join(''):'<option value="">Avval modellarni yuklang</option>';}; if(models.length)fill(); document.querySelector('#save').onclick=()=>{KitobchiStore.settings.set({apiKey:document.querySelector('#key').value.trim(),modelName:select.value});toast('Sozlamalar saqlandi');}; document.querySelector('#refresh').onclick=async()=>{const b=document.querySelector('#refresh');b.disabled=true;try{models=await KitobchiAPI.models();fill();document.querySelector('#modelStatus').textContent=`${models.length} ta model topildi.`;}catch(e){document.querySelector('#modelStatus').textContent=e.message;}finally{b.disabled=false;}}; bindNav(); }
  async function resumeJob(){ const job=getJob(); if(!job || job.status!=='running') return; active=KitobchiStore.projects.get(job.projectId); if(!active) return clearJob(); route='workspace'; render(); if(job.kind==='content') { await generateContent(); return; } if(job.kind==='chat') { const input=job.prompt; try { if(!models.length) models=await KitobchiAPI.models(); const chosen=KitobchiStore.settings.get().modelName||models[0]?.name?.replace('models/','')||''; const answer=await KitobchiAPI.generateResilient(input,chosen,(job.baseMessages||[]).map(m=>({role:m.role==='ai'?'model':'user',parts:[{text:m.text}]})),{maxContinuations:8}); active.messages.push({role:'ai',text:answer}); saveActive(); setJob({status:'done',stage:'Yakunlandi',progress:100,step:5}); setTimeout(clearJob,1800); render(); } catch(e){setJob({status:'error',stage:'Qayta urinib ko‘ring',error:e.message});} } }
  back.onclick=()=>{ if(route!=='home'){route='home';render();} }; settingsBtn.onclick=()=>{route='settings';render();}; window.addEventListener('online',resumeJob); document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible') resumeJob();}); render(); setTimeout(resumeJob,250);
})();