/* Kitobchi — mobil UI va ekranlar */
(() => {
  const screen = document.querySelector('#screen'), back = document.querySelector('#backBtn'), settingsBtn = document.querySelector('#settingsBtn');
  let route = 'home', active = null, models = [];
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const toast = s => { const t=document.querySelector('#toast'); t.textContent=s; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2800); };
  const id = () => Date.now().toString(36);
  function render(){ back.style.visibility=route==='home'?'hidden':'visible'; settingsBtn.style.visibility=route==='settings'?'hidden':'visible'; route==='home'?home():route==='create'?create():route==='workspace'?workspace():settings(); }
  function home(){ const ps=KitobchiStore.projects.list(); screen.innerHTML=`<section class="hero"><p class="eyebrow">IJOD UCHUN MAYDON</p><h1>G‘oyangizni<br><em>kitobga aylantiring.</em></h1><p class="muted">AI bilan yozing, bezang va birgina bosishda ulashing.</p><button class="primary wide" id="new">＋ Yangi loyiha</button></section><div class="section-head"><h2>Loyihalar</h2><span>${ps.length}</span></div><div class="cards">${ps.length?ps.map(p=>`<button class="project-card" data-id="${p.id}"><span class="project-icon">${p.type==='book'?'▤':p.type==='slides'?'▥':'▧'}</span><span><b>${esc(p.title)}</b><small>${esc(p.typeLabel||'Kitob')} · ${new Date(p.updatedAt||Date.now()).toLocaleDateString('uz-UZ')}</small></span><i>›</i></button>`).join(''):`<div class="empty"><div>✦</div><p>Hali loyiha yo‘q</p><small>Birinchi g‘oyangizni hoziroq boshlang.</small></div>`}</div><nav class="bottom-nav"><button class="active">⌂<small>Bosh sahifa</small></button><button id="navSettings">⚙<small>Sozlamalar</small></button></nav>`; document.querySelector('#new').onclick=()=>{route='create';render()}; document.querySelector('#navSettings').onclick=()=>{route='settings';render()}; document.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>{active=KitobchiStore.projects.get(x.dataset.id);route='workspace';render()}); }
  function create(){ screen.innerHTML=`<section class="page"><p class="eyebrow">YANGI LOYIHA</p><h1>Nima yaratamiz?</h1><p class="muted">G‘oyangizni yozing. Kitobchi uni savollar bilan aniq loyihaga aylantiradi.</p><div class="type-grid"><button class="type selected" data-type="book">📖<b>Kitob</b><small>Hikoya, roman, qo‘llanma</small></button><button class="type" data-type="slides">▥<b>Slaydlar</b><small>Ta’lim va taqdimot</small></button><button class="type" data-type="doc">▧<b>Hujjat</b><small>Universitet va biznes</small></button></div><label class="label">G‘oyangiz yoki buyruqingiz<textarea id="prompt" placeholder="Masalan: Bolalar uchun kosmos haqida rangli ertak..."></textarea></label><button class="primary wide" id="start">AI bilan boshlash →</button></section>`; let type='book';document.querySelectorAll('.type').forEach(b=>b.onclick=()=>{document.querySelectorAll('.type').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');type=b.dataset.type});document.querySelector('#start').onclick=()=>{const p=document.querySelector('#prompt').value.trim();if(!p)return toast('Avval g‘oyangizni yozing.');active={id:id(),title:p.slice(0,36),type,typeLabel:type==='book'?'Kitob':type==='slides'?'Slaydlar':'Hujjat',prompt:p,updatedAt:Date.now(),messages:[],pages:[]};KitobchiStore.projects.create(active);route='workspace';render()}; }
  function workspace(){ const p=active||{};screen.innerHTML=`<section class="workspace"><div class="work-title"><div><p class="eyebrow">${esc(p.typeLabel||'LOYIHA')}</p><h1>${esc(p.title)}</h1></div><button class="more" id="delete">⋮</button></div><div class="tabs"><button class="tab active">AI suhbat</button><button class="tab" id="contentTab">Kontent</button><button class="tab" id="exportTab">Eksport</button></div><div id="workBody"><div class="chat" id="chat"><div class="bubble ai">Salom! G‘oyangizni ko‘rdim. Uni yaxshiroq tushunishim uchun bir nechta savol beraman. Qahramonlar, uslub va kim uchun ekanini aytib bera olasizmi?</div>${(p.messages||[]).map(m=>`<div class="bubble ${m.role}">${esc(m.text)}</div>`).join('')}</div><div class="composer"><textarea id="msg" placeholder="Buyruq yoki javob yozing..."></textarea><button class="send" id="send">↑</button></div></div></section>`;document.querySelector('#send').onclick=send;document.querySelector('#msg').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};document.querySelector('#contentTab').onclick=content;document.querySelector('#exportTab').onclick=exportView;document.querySelector('#delete').onclick=()=>{if(confirm('Loyihani o‘chirasizmi?')){KitobchiStore.projects.delete(p.id);route='home';render()}}; }
  async function send(){const input=document.querySelector('#msg'),text=input.value.trim();if(!text)return;active.messages=active.messages||[];active.messages.push({role:'user',text});input.value='';KitobchiStore.projects.update(active.id,active);render();let answer;try{if(!models.length)models=await KitobchiAPI.models();const chosen = KitobchiStore.settings.get().modelName || models[0]?.name?.replace('models/','') || '';
      const history = (active.messages || []).slice(0, -1).map(m => ({role:m.role === 'ai' ? 'model' : 'user', parts:[{text:m.text}]}));
      answer=await KitobchiAPI.generateResilient(text, chosen, history, {maxContinuations: 3});}catch(e){answer='Demo rejim: '+e.message+' AI javobidan so‘ng “Kontent” bo‘limida sahifalar tayyorlanadi.'}active.messages.push({role:'ai',text:answer});KitobchiStore.projects.update(active.id,active);render();}
  function content(){const p=active;screen.innerHTML=`<section class="page"><p class="eyebrow">${esc(p.typeLabel)}</p><h1>Kontent studiyasi</h1><p class="muted">Sahifalar, muqova va rasmlar uchun buyruqlar.</p><button class="primary wide" id="gen">✦ Kontentni yaratish</button><div class="content-list"><div class="feature"><span>🎨</span><b>Rangli sahifalar</b><small>Har bir betga alohida dizayn</small></div><div class="feature"><span>▣</span><b>Muqova yaratish</b><small>Rasm modeli bo‘lsa avtomatik</small></div><div class="feature"><span>🖼</span><b>Bet rasmlari</b><small>AI rasm promptlari bilan</small></div></div><div id="pages">${(p.pages||[]).map((x,i)=>`<article class="page-card"><b>${i+1}. ${esc(x.title)}</b><p>${esc(x.text)}</p></article>`).join('')}</div></section>`;document.querySelector('#gen').onclick=()=>{p.pages=[{title:'Kirish',text:p.prompt+' — ilhomlantiruvchi boshlanish.'},{title:'Asosiy g‘oya',text:'Bu bo‘lim uchun AI bilan batafsil matn va rasm prompti yaratiladi.'},{title:'Yakun',text:'O‘quvchiga qoladigan iliq xulosa.'}];KitobchiStore.projects.update(p.id,p);toast('3 ta sahifa tayyorlandi');content()}; }
  function exportView(){const p=active;screen.innerHTML=`<section class="page"><p class="eyebrow">TAYYORLASH</p><h1>Yuklab oling yoki yuboring</h1><p class="muted">Loyihangiz telefoningizda saqlangan.</p><div class="export-grid"><button class="export" id="html">HTML kitob<small>Brauzerda ochiladi</small></button><button class="export" id="json">JSON loyiha<small>Zaxira nusxa</small></button><button class="export" id="pdf">Print / PDF<small>PDF sifatida saqlash</small></button><button class="export" id="share">Ulashish<small>Telegram va boshqa ilovalar</small></button></div></section>`;const html=`<html><meta charset="utf-8"><body><h1>${esc(p.title)}</h1>${(p.pages||[]).map(x=>`<h2>${esc(x.title)}</h2><p>${esc(x.text)}</p>`).join('')}</body></html>`;document.querySelector('#html').onclick=()=>KitobchiStore.export.exportHTML(html,'kitobchi.html');document.querySelector('#json').onclick=()=>KitobchiStore.export.exportJSON(p,'kitobchi.json');document.querySelector('#pdf').onclick=()=>KitobchiStore.export.exportPDF(html,p.title);document.querySelector('#share').onclick=()=>KitobchiStore.export.shareOrDownload(html,'kitobchi.html'); }
  function settings(){const s=KitobchiStore.settings.get();screen.innerHTML=`<section class="page"><p class="eyebrow">SOZLAMALAR</p><h1>Kitobchini sozlang</h1><label class="label">Gemini API kaliti<input id="key" type="password" value="${esc(s.apiKey||'')}" placeholder="AIza..." /></label><p class="hint">Kalit faqat shu telefonda saqlanadi. Uni APK ichiga joylamang.</p><button class="primary wide" id="save">Saqlash</button><div class="setting-card"><b>Model tanlash</b><p class="muted">Ro‘yxat Gemini API’dan avtomatik yuklanadi. Hech qanday model nomi ilovaga yozilmagan.</p><select id="modelSelect"><option value="">Avval modellarni yuklang</option></select><button class="secondary" id="refresh">Modellarni yuklash</button><div id="modelStatus"></div></div></section>`;const select=document.querySelector('#modelSelect');
    function fill(){select.innerHTML=models.length?models.map(m=>{const name=(m.name||'').replace('models/','');return `<option value="${esc(name)}" ${name===s.modelName?'selected':''}>${esc(m.displayName||name)}</option>`}).join(''):'<option value="">Avval modellarni yuklang</option>';}
    if(models.length)fill();
    document.querySelector('#save').onclick=()=>{KitobchiStore.settings.set({apiKey:document.querySelector('#key').value.trim(),modelName:select.value});toast('Sozlamalar saqlandi')};document.querySelector('#refresh').onclick=async()=>{const button=document.querySelector('#refresh');button.disabled=true;try{models=await KitobchiAPI.models();fill();document.querySelector('#modelStatus').textContent=`${models.length} ta model topildi. Keraklisini tanlab saqlang.`}catch(e){document.querySelector('#modelStatus').textContent=e.message}finally{button.disabled=false}};}
  back.onclick=()=>{if(route==='home')return;route=route==='workspace'?'home':'home';render()};settingsBtn.onclick=()=>{route='settings';render()};render();
})();
